### ISSUE TITLE
Output the word `Test` in console?

### ISSUE THREAD

**Issue by joliver** [smartystreets/gunit#1]
How should this test log when output to the console:
```
TestA_Equals_B
```

Should it be `A equals B` or `Test A equals B`

For that matter do we want to change `equals` to `=`?

**Comment by mdwhatcott** [comment]
Honestly, I'm tempted to make all exported functions test functions and remove the whole "Test" prefix thing.

Regarding the replacement of `equals` to `==`, what about in this scenario:

`TestAShouldEqualB`

I think we should leave the test name alone for the most part (yes, we've already agreed on inserting apostrophes for common contractions).

But it's early in the game still.

**Comment by mdwhatcott** [comment]
Fixed by 309aeeaf8a9413d2f2d406f4598ed1ec0db0418b
