### ISSUE TITLE
gunit.RunSequential currently required when running Go 1.14

### ISSUE THREAD

**Issue by mdwhatcott** [smartystreets/gunit#28]
https://youtrack.jetbrains.com/issue/GO-8985

**Comment by joliver** [comment]
Isn't this fixed in Go 1.14.1?

**Comment by mdwhatcott** [comment]
Nope. I performed all my tests for the youtrack issue using go 1.14.1. I should have been more clear in the post. Also, I don't think it's a duplicate issue so I've got more work to do to get the message across. Stay tuned...

**Comment by mdwhatcott** [comment]
Unfortunately, we may have to make `RunSequential` the default (temporarily) if this drags on.

**Comment by mdwhatcott** [comment]
https://github.com/golang/go/issues/38050
