### ISSUE TITLE
Support multiple Setup and Teardown functions on a fixture

### ISSUE THREAD

**Issue by rhoegg** [smartystreets/gunit#31]
It would be nice to be able to run multiple independent `fixture.Setup*` and `fixture.Teardown*` functions.  My use case is a functional test of several interacting components together.

Here is my current workaround:
```
func (this *FunctionalFixture) Setup() {
	var wg sync.WaitGroup
	wg.Add(2)
	go func() {
		this.setup1()
		wg.Done()
	}()
	go func() {
		this.setup2()
		wg.Done()
	}()
        wg.Wait()
}
```

**Comment by rhoegg** [comment]
It looks like `fixture_runner.go` holds a single index for each of the setup and teardown functions.

**Comment by mdwhatcott** [comment]
@rhoegg - The functionality for running multiple synchronous methods is quite simple (see e44b077). Setup methods must start with `Setup` and teardown methods must start with `Teardown`.

My only concern is that execution order of setups/teardowns is determined by how the reflect package iterates over the method definitions. In my limited testing (in the last 2 mintues) it appears to be lexicographic. Not sure if that's good or bad.

Something else I wanted to clarify was whether you want multiple setup/teardown methods to run simultaneously? I'd rather not add any such concurrent support to gunit.

**Comment by rhoegg** [comment]
Thanks I'll try this out and report!

No I don't need them to be concurrent, I agree the execution order should not be salient to test results.  I'd even be OK with a `rand.Shuffle` on the indices, although that might be overdoing things.

**Comment by rhoegg** [comment]
That worked in my project, thanks!

**Comment by mdwhatcott** [comment]
So, the big question for me is this:

How is being able to define multiple `Setup` methods better than just having a single `Setup` method that calls subordinate methods?

```
func (this *Fixture) Setup1() { /* ... */ }
func (this *Fixture) Setup2() { /* ... */ }
```

vs. 

```
func (this *Fixture) Setup() {
    this.setupSomething()
    this.setupSomethingElse()
}
func (this *Fixture) setupSomething() { /* ... */ }
func (this *Fixture) setupSomethingElse() { /* ... */ }
```

**Comment by rhoegg** [comment]
Well for me it helps communicate that the methods are independent, including their execution order.  I've used the pattern in junit, with multiple `@Before` methods in functional tests to initialize the collaborators.

**Comment by rhoegg** [comment]
I'm still hoping this gets merged!

**Comment by mdwhatcott** [comment]
@rhoegg - So sorry, we won't be merging this.
